#!/usr/bin/env node
/** Generate build-only literal types from the offline bundle; never fetch. */
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';

const directory = new URL('../packages/am32-core/src/eeprom/', import.meta.url);
const text = await readFile(new URL('eeprom.json', directory), 'utf8');
const schema = JSON.parse(text);
const hash = createHash('sha256').update(text).digest('hex');
const compare = (a: string, b: string) => {
    const aa = a.split('.').map(Number); const bb = b.split('.').map(Number);
    return (aa[0]! - bb[0]!) || (aa[1]! - bb[1]!);
};
const layout: Record<string, unknown> = {};
for (const field of Object.values(schema.fields) as { alias?: string[]; offset: number; size: number; minEepromVersion?: number; maxEepromVersion?: number; minFirmwareVersion?: string; maxFirmwareVersion?: string }[]) {
    if (!field.alias?.[0] || (field.minEepromVersion ?? 0) > 3 || (field.maxEepromVersion ?? 255) < 3 ||
        compare(field.minFirmwareVersion ?? '0.0', '32.0') > 0 || compare(field.maxFirmwareVersion ?? '65535.65535', '32.0') < 0) { continue; }
    const { offset, size, minEepromVersion, maxEepromVersion } = field;
    layout[field.alias[0]] = { offset, size, ...(minEepromVersion === undefined ? {} : { minEepromVersion }), ...(maxEepromVersion === undefined ? {} : { maxEepromVersion }) };
}
layout.CAN_SETTINGS = { offset: 176, size: 16 };
const banner = '// Generated by scripts/gen-eeprom-layout.ts. Do not edit or commit.\n';
await writeFile(new URL('schema.generated.ts', directory), `${banner}import type { EepromSchema } from './schema';\nexport const BUNDLED_SCHEMA = ${JSON.stringify(schema, null, 4)} as EepromSchema;\nexport const BUNDLED_SCHEMA_SHA256 = '${hash}';\n`);
await writeFile(new URL('layout.generated.ts', directory), `${banner}export const EepromLayout = ${JSON.stringify(layout, null, 4)} as const;\n`);
